/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_newadc_adc */

#ifndef _Included_com_example_newadc_adc
#define _Included_com_example_newadc_adc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_newadc_adc
 * Method:    Open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_newadc_adc_Open
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_newadc_adc
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_newadc_adc_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_example_newadc_adc
 * Method:    Ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_newadc_adc_Ioctl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_newadc_adc
 * Method:    Read
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_newadc_adc_Read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif