/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neojet_scanner_key */

#ifndef _Included_com_topeet_relaytest_relay
#define _Included_com_topeet_relaytest_relay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_topeet_relaytest_relay
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_relaytest_relay_Open
  (JNIEnv *, jobject);

/*
 * Class:     com_topeet_relaytest_relay
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_relaytest_relay_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_topeet_relaytest_relay
 * Method:    Ioctl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_relaytest_relay_Ioctl
  (JNIEnv *, jobject, jint num, jint en);

#ifdef __cplusplus
}
#endif
#endif
