/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neojet_scanner_key */

#ifndef _Included_com_topeet_rfidtest_rfid
#define _Included_com_topeet_rfidtest_rfid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_topeet_rfidtest_rfid
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_rfidtest_rfid_Open
  (JNIEnv *, jobject);

/*
 * Class:     com_topeet_rfidtest_rfid
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_rfidtest_rfid_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_topeet_rfidtest_rfid
 * Method:    Ioctl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_topeet_rfidtest_rfid_Ioctl
  (JNIEnv *, jobject, jint num, jint en);

/*
 * Class:     com_topeet_rfidtest_rfid
 * Method:    Read
 * Signature: ()I
 */
JNIEXPORT jintArray JNICALL Java_com_topeet_rfidtest_rfid_Read
  (JNIEnv *, jobject);

/*
 * Class:     com_topeet_rfidtest_rfid
 * Method:    ReadCardNum
 * Signature: ()I
 */
JNIEXPORT jbyteArray JNICALL Java_com_topeet_rfidtest_rfid_ReadCardNum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
